DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `userid` BIGINT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(100) NULL DEFAULT NULL,
  `lname` VARCHAR(100) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(200) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `dept` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE UNIQUE INDEX `userid_UNIQUE` ON `user` (`userid` ASC);

CREATE UNIQUE INDEX `email_UNIQUE` ON `user` (`email` ASC);
